### ISSUE TITLE
Add support for raw VAST XML input instead of VAST tag URL

### ISSUE THREAD

**Issue by pietermees** [InteractiveAdvertisingBureau/VAST-Tester#1]
There are situations where a user might only have the VAST XML available, not hosted behind a tag URL. It would be great to add support for this scenario by allowing the user to paste in their VAST XML instead of the tag URL.

**Comment by timdp** [comment]
Indeed. I'm thinking:

- Turn the `<input>` into a `<textarea>` so people can paste their tag as both a URL and as XML (as well as any other textual format we want to support in the future, such as JSON).

- Intelligently detect the input type. A trivial implementation would be to treat any string starting with `<` as XML.

- If it's XML, prefix it with `data:text/xml,` so that it becomes a valid URI. IIRC, iab-vast-loader will happily pick that up as a VAST URI all the same and we shouldn't even need to base64-encode it.

Caveat: The tag URL currently lives in the location hash. Having a full XML document in there shouldn't be an issue, although it's going to be a bit unsightly, particularly when you share it. At some point, we should consider adding a URL shortener.

**Comment by timdp** [comment]
This is now supported. :tada:
