### ISSUE TITLE
Is there an on-line version available ?

### ISSUE THREAD

**Issue by DavidBabel** [InteractiveAdvertisingBureau/VAST-Tester#4]
Hey hi, i'm the maintainer of this module https://www.npmjs.com/package/vast-builder

I wonder if there is an online version of this VAST Tester somewhere ? Maybe you can add it in the project description if it is.

**Comment by timdp** [comment]
Let me start off by saying that I highly appreciate the effort of open source IAB tooling. I feel there are a lot of gaps that could be filled there.

For that reason, we at Zentrick actually have our own open source [iab-vast-model](https://www.npmjs.com/package/iab-vast-model), [iab-vast-parser](https://www.npmjs.com/package/iab-vast-parser), and [iab-vast-loader](https://www.npmjs.com/package/iab-vast-loader) packages. Those are also used in the tester's codebase because we originally authored it.

I currently don't see a lot of value in replacing the VAST loader, and it also seems like you wrote an in-memory VAST builder (similar to iab-vast-model) rather than something that fetches a VAST and gives you an in-memory representation (similar to iab-vast-loader). In the broader sense, it would be good to run all sorts of tests against all sorts of industry-standard codebases though.

The public version is at <https://vasttester.iabtechlab.com>. @samtingleff Since there's indeed no link, perhaps you could add the public URL as the website for this repo in GitHub's UI? We could also put it in the readme.

**Comment by DavidBabel** [comment]
Thanks for the url, that's what i was looking for.
