### ISSUE TITLE
Icons element in the VAST tester

### ISSUE THREAD

**Issue by stefansandulescu** [InteractiveAdvertisingBureau/VAST-Tester#5]
Hello,

Can you please tell me if the the tool available here: https://vasttester.iabtechlab.com/#/ has Industry Icon Support. If not, do you happen to know where I can test this feature? I tried on all the other VAST testers/validators I found but I can't make the Adchoice icon appear.
https://zutils.zedo.com/vastvalidator/#/vastInspector
https://www.vastinspector.com/
My VAST XML is:
```
<VAST version="3.0">
    <Ad id="20011">
        <Wrapper>
            <AdSystem version="4.0">iabtechlab</AdSystem>
            <VASTAdTagURI><![CDATA[https://raw.githubusercontent.com/InteractiveAdvertisingBureau/VAST_Samples/master/VAST%203.0%20Samples/Inline_Linear_Tag-test.xml]]></VASTAdTagURI>

            <Error>http://example.com/error</Error>

            <Impression>http://example.com/track/impression</Impression>
            <Creatives>
                <Creative id="5480" sequence="1">
                    <CompanionAds>
                        <Companion id="1232" width="100" height="150" assetWidth="250" assetHeight="200" expandedWidth="350" expandedHeight="250">
                            <StaticResource creativeType="image/png">
                                    <![CDATA[https://www.iab.com/wp-content/uploads/2014/09/iab-tech-lab-6-644x290.png]]>
                            </StaticResource>
                            <CompanionClickThrough>
                                <![CDATA[https://iabtechlab.com]]>
                            </CompanionClickThrough>
                        </Companion>
                    </CompanionAds>
                    <Linear>
                        <Icons>
                          <Icon program="AdChoices" width="50" height="50" xPosition="left" yPosition="top">
                            <StaticResource creativeType="image/png">
                              <![CDATA[https://youradchoices.com/DAA_style/YAC/Icon_White_Box.png]]>
                            </StaticResource>
                          </Icon>
                        </Icons>
                    </Linear>
                </Creative>
            </Creatives>
        </Wrapper>
    </Ad>
</VAST>
```

Thanks!

**Comment by timdp** [comment]
Icon support is a to-do, unfortunately. Sorry that the UI does not make that clear!

With Zedo and potentially other testers, I think what you may be experiencing is shortcomings around adding icons via a VAST wrapper. If I dump your `<Icons>` element into the sample `<InLine>` directly instead of using a `<Wrapper>`, Google's [Video Suite Inspector](https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector) does show the icon. With your wrapper code, it doesn't.

I take it you're looking to reliably add an icon via a wrapper tag though? It would definitely be interesting to have a support matrix for this and other features in various players and testers.

**Comment by stefansandulescu** [comment]
Thank you for the answer.
Yes, ideally I would like to add the icon via the wrapper tag. But at least I know now that my request should work with a player that has this feature enabled.
